#!/bin/bash 
cd $(cd $(dirname $0); pwd)
Day_now=$(date +%F)
RED='\033[0;31m'
SMAY='\033[0;36m'
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'

Version=`lsb_release -rs | cut -f1 -d"."`

echo -e "${SMAY}\n"
echo -e "████████"
echo -e "𝘏𝘢𝘴𝘴𝘢𝘯 𝘔𝘶𝘢𝘦𝘥"
echo -e "████████"
echo -e "${CNIL}"

memory_free=`awk '/^Mem/ {print $4}' <(free -m)`

if [ "$memory_free" -le 60 ]; then
echo -e "${RED}¦
¦ CAUTION:${WHITEC} Your RAM size is less than 60MB.
¦ NOW you can not install the SOURCE AlBaghdadi. \n
¦${WHITB}¦ YOUR RAM FREE SIZE IS : ${SMAY}${memory_free}MB${CNIL}"
exit ;
fi


PKG_OK=`/usr/bin/dpkg-query --show --showformat='${db:Status-Status}\n' 'redis-server'`
if [ "${PKG_OK}" == "installed" ]; then
if [ "$1" == "-R" ] ; then
GET_INSTALL="NO"
else
GET_INSTALL=$(redis-cli get AlBaghdadi_INSTALL)
fi
if [ "${GET_INSTALL}" == "Yes" ]; then
echo -e "
${SMAY}>> ${LSAMAY}Source AlBaghdadi${SMAY} is Already Installed ^_^ .\n${CNIL}"
sudo chmod +x ./run
sudo chmod +x ./TG
sudo ./run
exit;
fi 
fi

echo -e "${WHITB}\n¦ installing source ... \n\n\n\n${CNIL}"
sudo apt-get update -y
sudo apt-get upgrade -y
echo -e "\x1B[01;90m\n¦ software-properties-common installing ... \n\x1B[0m"
sudo apt-get install software-properties-common -y
echo -e "\x1B[01;90m\n¦ ubuntu-toolchain installing ...\n \x1B[0m"
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
echo -e "\x1B[01;90m\n¦ install Modiles Pkgs ... \n\n\x1B[0m"

sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y wget -y

if [ "$Version" == "18" ];then
echo -e "${WHITB}\n¦ Installing depedencies for ubuntu 18  ... \n${CNIL}"
cd /lib/x86_64-linux-gnu/ && sudo ln -s libreadline.so.7.0 libreadline.so.6
wget "TH3AlBaghdadi.com/installubuntu18/compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb" && sudo dpkg -i compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
rm compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
fi

echo -e "\x1B[01;90m\n¦ screen installing ... \n\x1B[0m"
sudo apt-get install screen -y
echo -e "\x1B[01;90m\n¦ libstdc++6 installing ... \n\x1B[0m"
sudo apt-get install libstdc++6 -y
echo -e "\x1B[01;90m\n¦ lua-lgi installing ... \n\x1B[0m"
sudo apt-get install lua-lgi -y
echo -e "\x1B[01;90m\n¦ libnotify installing ... \n\x1B[0m"
sudo apt-get install libnotify-dev -y
echo -e "\x1B[01;90m\n¦ redis-server start ...\n \x1B[0m"
sudo service redis-server start
sudo apt-get update -y
echo -e "\x1B[01;90m\n¦  g++-4.7 -y c++-4.7 installing ... \n\x1B[0m"
sudo apt-get install g++-4.7 -y c++-4.7
echo -e "\x1B[01;90m\n¦ install luarocks v3.0.4 ... \n\n\x1B[0m"
echo -e "\x1B[01;90m\n¦ Download luarocks v3.0.4 ... \n\x1B[0m"
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz
echo -e "\x1B[01;90m\n¦ Unzip File luarocks v2.2.2 ... \n\x1B[0m"
tar zxpf luarocks-2.2.2.tar.gz
echo -e "\x1B[01;90m\n¦ Cd To Folder luarocks -2.2.2 ... \n\x1B[0m"
cd luarocks-2.2.2
echo -e "\x1B[01;90m\n¦ ./configure ...\n \x1B[0m"
./configure && make && sudo make install
echo -e "\x1B[01;90m\n¦ luarocks installing luasec ...\n \x1B[0m"
sudo luarocks install luasec
echo -e "\x1B[01;90m\n¦ luarocks installing luasocket ...\n \x1B[0m"
sudo luarocks install luasocket
echo -e "\x1B[01;90m\n¦ luarocks installing luautf8 ...\n \x1B[0m"
sudo luarocks install luautf8
echo -e "\x1B[01;90m\n¦ Remove luarocks ... \n\x1B[0m"
cd .. ;sudo rm -fr ./luarocks*
echo -e "${WHITB}\n¦ Convert TimeZone To Asia/Baghdad  ... \n${CNIL}"
sudo timedatectl set-timezone Asia/Baghdad
cd && cd AlBaghdadi && sudo find . -type f -print0 | xargs -0 chmod +x
echo -e "\n
${SMAY}>> Installation ${LSAMAY}Source AlBaghdadi ${SMAY} Completed ^_^ .\n
Now I Have Information For Your Bot  \n
1- Enter Token Your Bot .
2- Enter Your UserName Sudo .
3- And End Press Enter To Run Source AlBaghdadi .\n\n
${RED}Note:${Yellow} Send \"/start\"${SMAY} To Your Bot For Show All Commands.${CNIL}"
sudo ./run
